##<b> The International Cricket Council (ICC) is the world governing body of cricket. It was founded as the Imperial Cricket Conference in 1909 by representatives from Australia, England and South Africa. It was renamed as the International Cricket Conference in 1965, and took up its current name in 1989. It organises world championship events such as Cricket World Cup, Women's Cricket World Cup, ICC T20 World Cup, ICC Women's T20 World Cup, ICC Champions Trophy and Under-19 Cricket World Cup.</b>

<br>

## <b> You recently got a lucky break in the field of Data Science. You got a job of Data Scientist at ICC. You are part of the Analytics Team which is involved in pre-match analyses, live-match analyses and post-match analyses. </b>

<br>

## <b>This data consists of 1417 T20 matches. Each row corresponds to a single T20 match. As a data scientist, you have to first explore the data and check its sanity. </b>

<br>

## <u><b>Further you are required to do some analyses :</b></u>
* ### Rename all the column names to their appropriate names, for example meta.created should be renamed as created_date
* ### Find out the top three venues which hosted the greatest number of matches.
* ### Find out the pair of cricket teams who played the most number of T20 matches against each other.
* ### Print the top five teams by their win percentages. Win percentage is defined as the number of matches won divided by the number of matches played and then multiplied by 100.
* ### Write a function to get the scorecard of each match. This function would take the innings value as argument and return two scorecard dataframes each for one team as shown below. So the first dataframe would contain the top 4 scorers of the team who batted first and the top 4 bowlers of the opponent team. And the second dataframe would contain the top 4 scorers of the team who batted second and the top 4 bowlers of the opponent team.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mp
import seaborn as sb

In [ ]:
dataset = pd.read_csv('International_T20_Data.csv', engine='python', on_bad_lines='warn')

In [ ]:
dataset.head()

,innings,meta.data_version,meta.created,meta.revision,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,info.overs,...,info.outcome.by.runs,info.match_type_number,info.neutral_venue,info.outcome.method,info.outcome.result,info.outcome.eliminator,info.supersubs.New Zealand,info.supersubs.South Africa,info.bowl_out,info.outcome.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-18,2,"[datetime.date(2017, 2, 17)]",male,T20,5.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-19,2,"[datetime.date(2017, 2, 19)]",male,T20,2.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-23,1,"[datetime.date(2017, 2, 22)]",male,T20,NaN,Australia,20,...,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.9,2016-09-12,1,"[datetime.date(2016, 9, 5)]",male,T20,NaN,Hong Kong,20,...,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.9,2016-06-19,1,"[datetime.date(2016, 6, 18)]",male,T20,NaN,Zimbabwe,20,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(1) Rename all the column names to their appropriate names, for example meta.created should be renamed as created_date

In [ ]:
new_column_names = {
    'meta.created': 'created_date',
    'meta.data_version': 'data_version',
    'meta.revision': 'data_revision',
    'info.dates': 'match_date',
    'info.gender': 'gender',
    'info.match_type': 'match_format',
    'info.outcome.by.wickets': 'outcome_by_wickets',
    'info.outcome.winner': 'winner',
    'info.overs': 'overs',
    'info.player_of_match': 'player_of_match',
    'info.teams': 'teams',
    'info.toss.decision': 'toss_decision',
    'info.toss.winner': 'toss_winner',
    'info.umpires': 'umpires',
    'info.venue': 'venue',
    'info.city': 'city',
    'info.outcome.by.runs': 'outcome_by_runs',
    'info.match_type_number': 'match_number',
    'info.neutral_venue': 'neutral_venue',
    'info.outcome.method': 'outcome_method',
    'info.outcome.result': 'outcome_result',
    'info.outcome.eliminator': 'outcome_eliminator',
    'info.supersubs.New Zealand': 'supersubs_new_zealand',
    'info.supersubs.South Africa': 'supersubs_south_africa',
    'info.bowl_out': 'bowl_out',
    'info.outcome.bowl_out': 'outcome_bowl_out'
}

dataset = dataset.rename(columns=new_column_names)
dataset.head()

,innings,data_version,created_date,data_revision,match_date,gender,match_format,outcome_by_wickets,winner,overs,...,outcome_by_runs,match_number,neutral_venue,outcome_method,outcome_result,outcome_eliminator,supersubs_new_zealand,supersubs_south_africa,bowl_out,outcome_bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-18,2,"[datetime.date(2017, 2, 17)]",male,T20,5.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-19,2,"[datetime.date(2017, 2, 19)]",male,T20,2.0,Sri Lanka,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.9,2017-02-23,1,"[datetime.date(2017, 2, 22)]",male,T20,NaN,Australia,20,...,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.9,2016-09-12,1,"[datetime.date(2016, 9, 5)]",male,T20,NaN,Hong Kong,20,...,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.9,2016-06-19,1,"[datetime.date(2016, 6, 18)]",male,T20,NaN,Zimbabwe,20,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(2) Find out the top three venues which hosted the greatest number of matches.

In [ ]:
top_venues = dataset['info.venue'].value_counts().head(3)
print(top_venues)

info.venue
Dubai International Cricket Stadium    62
Sheikh Zayed Stadium                   41
Shere Bangla National Stadium          39
Name: count, dtype: int64

(3) Find out the pair of cricket teams who played the most number of T20 matches against each other.

In [ ]:
import ast

dataset['teams'] = dataset['teams'].apply(ast.literal_eval)
dataset['teams'].apply(lambda x: tuple(sorted(x))).value_counts().head(1)

teams
(Australia, England)    45
Name: count, dtype: int64

(4) Print the top five teams by their win percentages. Win percentage is defined as the number of matches won divided by the number of matches played and then multiplied by 100.

In [ ]:
matches_played = dataset['teams'].explode().value_counts()
matches_won = dataset['winner'].value_counts()
win_percentage = (matches_won / matches_played) * 100
win_percentage.sort_values(ascending=False).head(5)

Belgium        100.000000
Spain           83.333333
Germany         76.470588
Namibia         73.529412
Afghanistan     68.000000
Name: count, dtype: float64

(5) Write a function to get the scorecard of each match. This function would take the innings value as argument and return two scorecard dataframes each for one team as shown below. So the first dataframe would contain the top 4 scorers of the team who batted first and the top 4 bowlers of the opponent team. And the second dataframe would contain the top 4 scorers of the team who batted second and the top 4 bowlers of the opponent team.

In [ ]:
def get_scorecard(data):

    # First innings
    bat1 = data[data['innings']==1].groupby('batter')['runs_off_bat'].sum().sort_values(ascending=False).head(4)
    bowl1 = data[data['innings']==1].groupby('bowler')['is_wicket'].sum().sort_values(ascending=False).head(4)

    scorecard1 = pd.concat([bat1, bowl1], axis=1)

    # Second innings
    bat2 = data[data['innings']==2].groupby('batter')['runs_off_bat'].sum().sort_values(ascending=False).head(4)
    bowl2 = data[data['innings']==2].groupby('bowler')['is_wicket'].sum().sort_values(ascending=False).head(4)

    scorecard2 = pd.concat([bat2, bowl2], axis=1)

    return scorecard1, scorecard2

In [77]:
for i in range(len(dataset)):

    match_innings_raw = dataset['innings'].iloc[i]

    match_innings_parsed = ast.literal_eval(match_innings_raw)

    rows = []
    for inning_index, inning_detail in enumerate(match_innings_parsed): # Use the parsed data
        for inning_name, inning_content in inning_detail.items():
            team = inning_content['team']
            deliveries = inning_content['deliveries']
            for delivery in deliveries:
                for over_ball, ball_data in delivery.items():
                    batsman = ball_data.get('batsman')
                    bowler = ball_data.get('bowler')
                    # Extract runs scored by batsman from the 'runs' dictionary, default to 0 if not found
                    runs_off_bat = ball_data.get('runs', {}).get('batsman', 0)
                    # Check if a wicket occurred in this delivery, assign 1 if yes, 0 if no
                    is_wicket = 1 if 'wicket' in ball_data else 0
                    rows.append({
                        'innings': inning_index + 1, # 'innings' column represents the inning number (1st, 2nd)
                        'team': team,
                        'batter': batsman,
                        'bowler': bowler,
                        'runs_off_bat': runs_off_bat,
                        'is_wicket': is_wicket
                    })

    match_data_for_scorecard = pd.DataFrame(rows)

    score1, score2 = get_scorecard(match_data_for_scorecard)

    print(f"\n\nMatch : {i+1}\n")
    print("Team 1 Score:\n")
    print(score1)
    print("\nTeam 2 Score:\n")
    print(score2)

Streaming output truncated to the last 5000 lines.
SJ Coyte              NaN        1.0


Match : 1232

Team 1 Score:

              runs_off_bat  is_wicket
MM Lanning            43.0        NaN
EJ Villani            32.0        NaN
AJ Blackwell          20.0        NaN
EA Perry              17.0        NaN
EJ Tice                NaN        2.0
CJ Metcalfe            NaN        1.0
KJ Garth               NaN        1.0
LK O'Reilly            NaN        1.0

Team 2 Score:

             runs_off_bat  is_wicket
CNIM Joyce           26.0        NaN
GH Lewis             23.0        NaN
KJ Garth             15.0        NaN
LK O'Reilly          13.0        NaN
EA Perry              NaN        2.0
GM Harris             NaN        2.0
RM Farrell            NaN        2.0
EA Osborne            NaN        1.0


Match : 1233

Team 1 Score:

              runs_off_bat  is_wicket
EA Perry              39.0        NaN
AJ Blackwell          20.0        NaN
JE Cameron            20.0        NaN
GM Harris             19.0        NaN
KJ Garth               NaN        3.0
L Delany               NaN        1.0
LK O'Reilly            NaN        1.0
LN McCarthy            NaN        1.0

Team 2 Score:

             runs_off_bat  is_wicket
IMHC Joyce           24.0        NaN
KJ Garth             15.0        NaN
L Delany             12.0        NaN
LK O'Reilly          10.0        NaN
JL Jonassen           NaN        3.0
EA Osborne            NaN        2.0
EA Perry              NaN        1.0
RM Farrell            NaN        1.0


Match : 1234

Team 1 Score:

             runs_off_bat  is_wicket
EJ Villani           80.0        NaN
EA Perry             55.0        NaN
GM Harris            39.0        NaN
EJ Tice               NaN        1.0
AJ Kenealy            NaN        0.0
CJ Metcalfe           NaN        0.0
IMHC Joyce            NaN        0.0

Team 2 Score:

             runs_off_bat  is_wicket
KJ Garth             30.0        NaN
LK O'Reilly          14.0        NaN
CNIM Joyce           12.0        NaN
GH Lewis             10.0        NaN
ML Schutt             NaN        3.0
JL Jonassen           NaN        2.0
EA Osborne            NaN        1.0
GM Harris             NaN        1.0


Match : 1235

Team 1 Score:

             runs_off_bat  is_wicket
JC Buttler           32.0        NaN
AD Hales             27.0        NaN
JJ Roy               15.0        NaN
CJ Jordan            15.0        NaN
Imran Tahir           NaN        4.0
KJ Abbott             NaN        2.0
D Wiese               NaN        1.0
K Rabada              NaN        1.0

Team 2 Score:

              runs_off_bat  is_wicket
F du Plessis          25.0        NaN
JP Duminy             23.0        NaN
HM Amla               22.0        NaN
RR Rossouw            18.0        NaN
CJ Jordan              NaN        3.0
MM Ali                 NaN        2.0
BA Stokes              NaN        1.0
AU Rashid              NaN        1.0


Match : 1236

Team 1 Score:

             runs_off_bat  is_wicket
JC Buttler           54.0        NaN
EJG Morgan           38.0        NaN
JE Root              34.0        NaN
AD Hales             16.0        NaN
KJ Abbott             NaN        4.0
CH Morris             NaN        2.0
K Rabada              NaN        2.0
Imran Tahir           NaN        2.0

Team 2 Score:

                runs_off_bat  is_wicket
AB de Villiers          71.0        NaN
HM Amla                 69.0        NaN
F du Plessis            22.0        NaN
AU Rashid                NaN        1.0
BA Stokes                NaN        0.0
CJ Jordan                NaN        0.0
MM Ali                   NaN        0.0


Match : 1237

Team 1 Score:

              runs_off_bat  is_wicket
Sompal Kami           40.0        NaN
G Malla                5.0        NaN
SP Gauchan             5.0        NaN
NB Budayair            5.0        NaN
Aizaz Khan             NaN        2.0
Haseeb Amjad           NaN        2.0
Irfan Ahmed            NaN        2.0
Nadeem Ahmed           NaN        2.0

Team 2 Score:

              runs_off_bat  is_wicket
Aizaz Khan            21.0        NaN
Anas Khan             21.0        NaN
Tanwir Afzal           9.0        NaN
Irfan Ahmed            8.0        NaN
A Bhattarai            NaN        2.0
SP Gauchan             NaN        2.0
Sagar Pun              NaN        2.0
P Khadka               NaN        1.0


Match : 1238

Team 1 Score:

                   runs_off_bat  is_wicket
Sana Mir                   48.0        NaN
Javeria Khan               25.0        NaN
Nain Abidi                 13.0        NaN
Bismah Maroof               7.0        NaN
HAM Samuddika               NaN        3.0
I Ranaweera                 NaN        2.0
MGMCP Gunawardene           NaN        1.0
BMSM Kumari                 NaN        0.0

Team 2 Score:

                   runs_off_bat  is_wicket
MGMCP Gunawardene          14.0        NaN
KADA Kanchana              10.0        NaN
SS Weerakkody               9.0        NaN
LE Kaushalya                7.0        NaN
Sana Mir                    NaN        4.0
Bismah Maroof               NaN        2.0
Nida Dar                    NaN        2.0
Sadia Yousuf                NaN        1.0


Match : 1239

Team 1 Score:

                   runs_off_bat  is_wicket
Bismah Maroof              46.0        NaN
Sana Mir                   20.0        NaN
Nida Dar                   15.0        NaN
Marina Iqbal                6.0        NaN
KDU Prabodhani              NaN        4.0
I Ranaweera                 NaN        2.0
MGMCP Gunawardene           NaN        2.0
LE Kaushalya                NaN        1.0

Team 2 Score:

                runs_off_bat  is_wicket
AC Jayangani            44.0        NaN
LE Kaushalya            23.0        NaN
MADD Surangika          18.0        NaN
SS Weerakkody            6.0        NaN
Nida Dar                 NaN        2.0
Bismah Maroof            NaN        1.0
Sana Mir                 NaN        1.0
Sadia Yousuf             NaN        1.0


Match : 1240

Team 1 Score:

                  runs_off_bat  is_wicket
F du Plessis              79.0        NaN
RR Rossouw                31.0        NaN
JP Duminy                 18.0        NaN
Q de Kock                 12.0        NaN
Arafat Sunny               NaN        2.0
Nasir Hossain              NaN        1.0
Shakib Al Hasan            NaN        1.0
Mashrafe Mortaza           NaN        0.0

Team 2 Score:

                 runs_off_bat  is_wicket
Shakib Al Hasan          26.0        NaN
Liton Das                22.0        NaN
Mushfiqur Rahim          17.0        NaN
Soumya Sarkar             7.0        NaN
D Wiese                   NaN        3.0
JP Duminy                 NaN        2.0
K Rabada                  NaN        2.0
AM Phangiso               NaN        1.0


Match : 1241

Team 1 Score:

                   runs_off_bat  is_wicket
Q de Kock                  44.0        NaN
AB de Villiers             40.0        NaN
DA Miller                  30.0        NaN
RR Rossouw                 19.0        NaN
Nasir Hossain               NaN        2.0
Arafat Sunny                NaN        1.0
Mustafizur Rahman           NaN        1.0
Mashrafe Mortaza            NaN        0.0

Team 2 Score:

                  runs_off_bat  is_wicket
Soumya Sarkar             37.0        NaN
Rony Talukdar             21.0        NaN
Mushfiqur Rahim           19.0        NaN
Mashrafe Mortaza          17.0        NaN
AM Phangiso                NaN        3.0
E Leie                     NaN        3.0
KJ Abbott                  NaN        3.0
WD Parnell                 NaN        1.0


Match : 1242

Team 1 Score:

               runs_off_bat  is_wicket
M du Preez             41.0        NaN
D van Niekerk          25.0        NaN
NA Moodley             17.0        NaN
T Chetty                8.0        NaN
Asmavia Iqbal           NaN        3.0
Anam Amin               NaN        1.0
Nida Dar                NaN        1.0
Sana Mir                NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
Marina Iqbal           42.0        NaN
Asmavia Iqbal          23.0        NaN
Bismah Maroof          19.0        NaN
Nida Dar               10.0        NaN
S Luus                  NaN        3.0
D van Niekerk           NaN        1.0
S Ismail                NaN        1.0
A Khaka                 NaN        0.0


Match : 1243

Team 1 Score:

                 runs_off_bat  is_wicket
S Luus                   23.0        NaN
L Lee                    22.0        NaN
D van Niekerk            14.0        NaN
M du Preez               12.0        NaN
Anam Amin                 NaN        2.0
Asmavia Iqbal             NaN        2.0
Nida Dar                  NaN        1.0
Sumaiya Siddiqi           NaN        1.0

Team 2 Score:

               runs_off_bat  is_wicket
Bismah Maroof          30.0        NaN
Asmavia Iqbal          21.0        NaN
Iram Javed             15.0        NaN
Javeria Khan            5.0        NaN
D van Niekerk           NaN        2.0
Y Fourie                NaN        1.0
S Luus                  NaN        1.0
M Daniels               NaN        0.0


Match : 1244

Team 1 Score:

               runs_off_bat  is_wicket
Bismah Maroof          34.0        NaN
Asmavia Iqbal          31.0        NaN
Marina Iqbal           15.0        NaN
Nida Dar               15.0        NaN
D van Niekerk           NaN        3.0
M Daniels               NaN        2.0
S Ismail                NaN        2.0
MM Letsoalo             NaN        0.0

Team 2 Score:

               runs_off_bat  is_wicket
D van Niekerk          67.0        NaN
M du Preez             13.0        NaN
T Chetty               13.0        NaN
L Lee                  10.0        NaN
Anam Amin               NaN        2.0
Asmavia Iqbal           NaN        1.0
Bismah Maroof           NaN        0.0
Iram Javed              NaN        0.0


Match : 1245

Team 1 Score:

               runs_off_bat  is_wicket
MJ Guptill             42.0        NaN
KS Williamson          42.0        NaN
GH Worker              28.0        NaN
TWM Latham             12.0        NaN
D Wiese                 NaN        3.0
AM Phangiso             NaN        2.0
K Rabada                NaN        2.0
M Morkel                NaN        1.0

Team 2 Score:

                runs_off_bat  is_wicket
HM Amla                 48.0        NaN
RR Rossouw              38.0        NaN
AB de Villiers          33.0        NaN
MN van Wyk              19.0        NaN
AF Milne                 NaN        1.0
DAJ Bracewell            NaN        1.0
GH Worker                NaN        1.0
MJ McClenaghan           NaN        1.0


Match : 1246

Team 1 Score:

               runs_off_bat  is_wicket
MJ Guptill             60.0        NaN
JDS Neesham            28.0        NaN
KS Williamson          25.0        NaN
GD Elliott             20.0        NaN
K Rabada                NaN        3.0
AM Phangiso             NaN        1.0
D Wiese                 NaN        1.0
E Leie                  NaN        1.0

Team 2 Score:

                runs_off_bat  is_wicket
F Behardien             36.0        NaN
DA Miller               29.0        NaN
RR Rossouw              26.0        NaN
AB de Villiers          15.0        NaN
MJ McClenaghan           NaN        2.0
IS Sodhi                 NaN        2.0
NL McCullum              NaN        2.0
AF Milne                 NaN        1.0


Match : 1247

Team 1 Score:

                  runs_off_bat  is_wicket
SR Taylor                 40.0        NaN
MR Aguilleira             28.0        NaN
B Cooper                  17.0        NaN
CA Henry                  11.0        NaN
SS Weerakkody              NaN        2.0
BMSM Kumari                NaN        1.0
KDU Prabodhani             NaN        1.0
HASD Siriwardene           NaN        1.0

Team 2 Score:

                  runs_off_bat  is_wicket
MADD Surangika            28.0        NaN
AC Jayangani              17.0        NaN
HASD Siriwardene          17.0        NaN
LE Kaushalya              16.0        NaN
A Mohammed                 NaN        2.0
SACA King                  NaN        2.0
ASS Fletcher               NaN        1.0
SR Taylor                  NaN        1.0


Match : 1248

Team 1 Score:

                  runs_off_bat  is_wicket
MADD Surangika            30.0        NaN
AC Jayangani              27.0        NaN
HASD Siriwardene          26.0        NaN
MDN Hansika               21.0        NaN
SR Taylor                  NaN        2.0
ASS Fletcher               NaN        1.0
A Mohammed                 NaN        1.0
HK Matthews                NaN        1.0

Team 2 Score:

                  runs_off_bat  is_wicket
SR Taylor                 59.0        NaN
DJS Dottin                51.0        NaN
HK Matthews                7.0        NaN
B Cooper                   6.0        NaN
HAM Samuddika              NaN        1.0
KDU Prabodhani             NaN        1.0
BMSM Kumari                NaN        0.0
HASD Siriwardene           NaN        0.0


Match : 1249

Team 1 Score:

                   runs_off_bat  is_wicket
AC Jayangani               43.0        NaN
MGMCP Gunawardene          10.0        NaN
BMSM Kumari                 7.0        NaN
HASD Siriwardene            2.0        NaN
HK Matthews                 NaN        4.0
A Mohammed                  NaN        2.0
ASS Fletcher                NaN        2.0
TD Smartt                   NaN        1.0

Team 2 Score:

                  runs_off_bat  is_wicket
SR Taylor                 38.0        NaN
HK Matthews               32.0        NaN
I Ranaweera                NaN        1.0
BMSM Kumari                NaN        0.0
HASD Siriwardene           NaN        0.0
KDU Prabodhani             NaN        0.0


Match : 1250

Team 1 Score:

                   runs_off_bat  is_wicket
Mukhtar Ahmed              37.0        NaN
Haris Sohail               30.0        NaN
Mohammad Hafeez            26.0        NaN
Ahmed Shehzad              17.0        NaN
Taskin Ahmed                NaN        2.0
Mustafizur Rahman           NaN        2.0
Arafat Sunny                NaN        1.0
Mashrafe Mortaza            NaN        0.0

Team 2 Score:

                 runs_off_bat  is_wicket
Shakib Al Hasan          57.0        NaN
Sabbir Rahman            51.0        NaN
Mushfiqur Rahim          19.0        NaN
Tamim Iqbal              14.0        NaN
Mohammad Hafeez           NaN        1.0
Wahab Riaz                NaN        1.0
Umar Gul                  NaN        1.0
Saeed Ajmal               NaN        0.0


Match : 1251

Team 1 Score:

                 runs_off_bat  is_wicket
Ahmed Shehzad            46.0        NaN
Shoaib Malik             46.0        NaN
Umar Akmal               46.0        NaN
Mohammad Hafeez          17.0        NaN
NLTC Perera               NaN        2.0
AD Mathews                NaN        1.0
B Fernando                NaN        1.0
SL Malinga                NaN        1.0

Team 2 Score:

                 runs_off_bat  is_wicket
TAM Siriwardana          35.0        NaN
DM de Silva              31.0        NaN
CK Kapugedera            31.0        NaN
AD Mathews               23.0        NaN
Sohail Tanvir             NaN        3.0
Anwar Ali                 NaN        2.0
Imad Wasim                NaN        1.0
Shoaib Malik              NaN        1.0


Match : 1252

Team 1 Score:

                  runs_off_bat  is_wicket
CK Kapugedera             48.0        NaN
GSNFG Jayasuriya          40.0        NaN
TAM Siriwardana           23.0        NaN
MDKJ Perera               19.0        NaN
Shoaib Malik               NaN        2.0
Sohail Tanvir              NaN        2.0
Shahid Afridi              NaN        1.0
Anwar Ali                  NaN        1.0

Team 2 Score:

                  runs_off_bat  is_wicket
Anwar Ali                 46.0        NaN
Shahid Afridi             45.0        NaN
Imad Wasim                24.0        NaN
Mohammad Rizwan           17.0        NaN
B Fernando                 NaN        2.0
GSNFG Jayasuriya           NaN        2.0
NLTC Perera                NaN        2.0
SL Malinga                 NaN        2.0


Match : 1253

Team 1 Score:

               runs_off_bat  is_wicket
E Chigumbura           54.0        NaN
H Masakadza            43.0        NaN
Sikandar Raza          17.0        NaN
SC Williams            16.0        NaN
Mohammad Sami           NaN        3.0
Wahab Riaz              NaN        2.0
Shoaib Malik            NaN        1.0
Anwar Ali               NaN        0.0

Team 2 Score:

                 runs_off_bat  is_wicket
Mukhtar Ahmed            83.0        NaN
Ahmed Shehzad            55.0        NaN
Mohammad Hafeez          12.0        NaN
Shoaib Malik              7.0        NaN
AG Cremer                 NaN        2.0
BV Vitori                 NaN        1.0
SC Williams               NaN        1.0
T Panyangara              NaN        1.0


Match : 1254

Team 1 Score:

               runs_off_bat  is_wicket
SC Williams            58.0        NaN
V Sibanda              49.0        NaN
H Masakadza            39.0        NaN
E Chigumbura           21.0        NaN
Shahid Afridi           NaN        1.0
Mohammad Sami           NaN        1.0
Shoaib Malik            NaN        1.0
Anwar Ali               NaN        0.0

Team 2 Score:

               runs_off_bat  is_wicket
Mukhtar Ahmed          62.0        NaN
Umar Akmal             30.0        NaN
Nauman Anwar           18.0        NaN
Ahmed Shehzad          18.0        NaN
P Utseya                NaN        2.0
CB Mpofu                NaN        2.0
SC Williams             NaN        2.0
BV Vitori               NaN        1.0


Match : 1255

Team 1 Score:

                      runs_off_bat  is_wicket
Mohammad Naveed               19.0        NaN
Faizan Asif                   17.0        NaN
Amjad Ali                     14.0        NaN
Mohammad Shahzad (2)          14.0        NaN
MA Leask                       NaN        3.0
MRJ Watt                       NaN        3.0
AC Evans                       NaN        2.0
SM Sharif                      NaN        2.0

Team 2 Score:

                      runs_off_bat  is_wicket
HG Munsey                     62.0        NaN
KJ Coetzer                    39.0        NaN
CS MacLeod                     7.0        NaN
Mohammad Naveed                NaN        1.0
AM Guruge                      NaN        0.0
Amjad Javed                    NaN        0.0
Mohammad Shahzad (2)           NaN        0.0


Match : 1256

Team 1 Score:

                    runs_off_bat  is_wicket
Samiullah Shenwari          44.0        NaN
Mohammad Nabi               33.0        NaN
Najibullah Zadran           33.0        NaN
Nawroz Mangal               29.0        NaN
Ahsan Malik                  NaN        3.0
RE van der Merwe             NaN        2.0
Mudassar Bukhari             NaN        2.0
MR Swart                     NaN        0.0

Team 2 Score:

                    runs_off_bat  is_wicket
BN Cooper                   36.0        NaN
W Barresi                   18.0        NaN
MR Swart                    18.0        NaN
MJG Rippon                  17.0        NaN
Dawlat Zadran                NaN        3.0
Sharafuddin Ashraf           NaN        3.0
Mohammad Nabi                NaN        2.0
Hamid Hassan                 NaN        1.0


Match : 1257

Team 1 Score:

                      runs_off_bat  is_wicket
Mohammad Shahzad (2)          43.0        NaN
Shaiman Anwar                 35.0        NaN
Faizan Asif                   28.0        NaN
Abdul Shakoor                 20.0        NaN
Mirwais Ashraf                 NaN        3.0
Hamid Hassan                   NaN        2.0
Dawlat Zadran                  NaN        1.0
Mohammad Nabi                  NaN        0.0

Team 2 Score:

                    runs_off_bat  is_wicket
Mohammad Shahzad            74.0        NaN
Asghar Stanikzai            44.0        NaN
Samiullah Shenwari          30.0        NaN
Nawroz Mangal               15.0        NaN
Amjad Javed                  NaN        1.0